### ISSUE TITLE
He changed the configuration of the new edition.

### ISSUE THREAD

**Issue by shijunti19** [sidneywang/rsbind#1]
https://developer.android.com/ndk/guides/other_build_systems

As of NDK r19, the toolchains installed by default with the NDK may be used in-place. The make_standalone_toolchain.py script is no longer needed for interfacing with arbitrary build systems.

To ensure that you build for the correct architecture, either pass the appropriate target with -target when invoking Clang, or invoke the target-prefixed Clang. For example, to compile for 64-bit ARM Android with a minSdkVersion of 21, either of the following will work and you may use whichever you find most convenient:

**Comment by sidneywang** [comment]
Thanks for your advice, I had noticed the changes of NDK in new versions  and will try it and make an addition in the guide, but now you can install NDK following the guide in developer.android.com or just install older version.

**Comment by hdqb** [comment]
when will it be active this archive has been inactive for a long time?

**Comment by sidneywang** [comment]
> 

I  want to reactive this repo this year.

**Comment by sidneywang** [comment]
Have integrated ndk-build
