### ISSUE TITLE
iOS Demo Failed

### ISSUE THREAD

**Issue by brightsider** [sidneywang/rsbind#2]
module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler

**Comment by sidneywang** [comment]
> module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler

Hi, @brightsider 
    Could you describe the issues more detailed? It works in my computer with this steps.
    1. Install cargo bin with "cargo install --force"
    2. In demo directory, run "rsbind . ios all"
    3. Run ./cp.sh, copy rustlib.framework to ios-demo
   4. Change ios-demo language to swift 5.
   5. It works.

**Comment by sidneywang** [comment]
> module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler

Maybe your rsbind bin is not the latest version? 
Please run "cargo install --force"  once again.

**Comment by brightsider** [comment]
I fixed this by upgrade swift version in tools-swift-gen project

**Comment by sidneywang** [comment]
> I fixed this by upgrade swift version in tools-swift-gen project

There is no such problem in my computer and xcode, could you please provide the detailed error infomation and a pull request to fix it?
