### ISSUE TITLE
对.a文件的体积影响很大

### ISSUE THREAD

**Issue by tNobuta** [sidneywang/rsbind#24]
你好，我这边手头的核心代码本身生成的.a size在优化后是2.6mb, 发现用rsbind生成bridge代码后再统一生成.a文件 size直接就涨到9mb, 是否是引用了额外的std symbol导致的，请问有没有什么手段能把目前用不到的一些bridge能力和相关依赖去掉。。

**Comment by afoxer-com** [comment]
2.6M你加了X86了吗。

**Comment by afoxer-com** [comment]
[ios] 
rustc_param = ""  
arch = ["aarch64-apple-ios", "x86_64-apple-ios"]  
release = true  
features_def = []


可以再rsbind.toml配置下arch，只保留aarch64试试？
