### ISSUE TITLE
How can I debug Rust on Android

### ISSUE THREAD

**Issue by creasexul** [sidneywang/rsbind#4]
I'm trying to develop Android apps by Rust. But when I try to debug it, I can't find the direct way to touch this, only by command lines.
Is there any way more?

**Comment by sidneywang** [comment]
> I'm trying to develop Android apps by Rust. But when I try to debug it, I can't find the direct way to touch this, only by command lines.
> Is there any way more?

I think Clion with plugin can debug rust, but in android I think it's more difficult, you can have a try.

**Comment by creasexul** [comment]
Thanks, I just try with lldb in AS(Android Studio), it works but not very well.
I'm looking for some way to use AS's lldb in CLion so that I can use AS's build chain in debugging rust.

**Comment by tNobuta** [comment]
> Thanks, I just try with lldb in AS(Android Studio), it works but not very well.
> I'm looking for some way to use AS's lldb in CLion so that I can use AS's build chain in debugging rust.

can you debug rust so file on android via lldb command line tool? I can not add breakpoint by file:line, because it report: "Unable to resolve breakpoint to any actual locations."
