### ISSUE TITLE
Config contract and imp in rsbind.toml.

### ISSUE THREAD

**Issue by afoxer-com** [sidneywang/rsbind#48]

**Comment by tNobuta** [comment]
need this feature..

**Comment by afoxer-com** [comment]
OK! Make priority higher!

**Comment by afoxer-com** [comment]
Can join the QQ group (README), if can.

**Comment by tNobuta** [comment]
why the discord invite url was expired

**Comment by afoxer-com** [comment]
Discord is hard to connect, I cant connect it for two weeks.

**Comment by tNobuta** [comment]
> 

你需要翻墙 = =

**Comment by afoxer-com** [comment]
公司VPN

**Comment by afoxer-com** [comment]
I find an issue when doing the implementation, I can not get the mod path from a file path, with which I can import this mod to the bridge crate.

**Comment by afoxer-com** [comment]
> 

So Maybe we can just config a first-level dir or file name.

**Comment by afoxer-com** [comment]
![image](https://user-images.githubusercontent.com/105094159/204019287-c39679a1-244d-4d2c-aa0d-829d0a503832.png)

**Comment by afoxer-com** [comment]
> ![image](https://user-images.githubusercontent.com/105094159/204019287-c39679a1-244d-4d2c-aa0d-829d0a503832.png)

What I can do is to config the contract dir/file name and imp dir/file name.

**Comment by afoxer-com** [comment]
https://github.com/afoxer-com/rsbind/pull/63

**Comment by tNobuta** [comment]
或许也可以针对不同平台配置不同的文件名或者目录，比如我现在遇到的场景就是针对ios和android 在contract内定义的trait 方法不那么一样

**Comment by afoxer-com** [comment]
It make sense.

**Comment by afoxer-com** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/105094159/204082428-fcbcaf43-1a3d-40f8-9046-8a909e992f18.png">

**Comment by afoxer-com** [comment]
> <img alt="image" width="651" src="https://user-images.githubusercontent.com/105094159/204082428-fcbcaf43-1a3d-40f8-9046-8a909e992f18.png">

Now you can config in every target.

**Comment by afoxer-com** [comment]
https://github.com/afoxer-com/rsbind/pull/64

**Comment by afoxer-com** [comment]
Please try and if any questions, don't hesitate to ask.
