### ISSUE TITLE
"test_arg_callback"在android项目中调用出现闪退，其他方法都能正常调用

### ISSUE THREAD

**Issue by tNobuta** [sidneywang/rsbind#7]
你好，我在android demo工程中尝试callback调用，必现闪退，其他test方法调用倒是ok的，调用代码和闪退信息如下：

`TestContract1.test_arg_callback(new Callback() {
            @Override
            public byte on_callback_u8(byte arg1) {
                return 0;
            }

            @Override
            public byte on_callback_i8(byte arg1) {
                return 0;
            }

            @Override
            public int on_callback(int arg1, String arg2, boolean arg3, float arg4, double arg5) {
                return 0;
            }

            @Override
            public boolean on_callback2(boolean arg1) {
                return false;
            }

            @Override
            public boolean on_callback_complex(StructSimple arg1) {
                return false;
            }

            @Override
            public boolean on_callback_arg_vec(StructSimple[] arg1) {
                return false;
            }

            @Override
            public boolean on_callback_arg_vec_simple(String[] arg1) {
                return false;
            }

            @Override
            public void on_empty_callback() {

            }
        });`

崩溃信息
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 10286 (ple.com.android), pid 10286 (ple.com.android)

**Comment by sidneywang** [comment]
感谢，这几天我也发现了这个问题。在以前的Rust版本是没问题的，怀疑是Rust的Box < Callback > 被废弃导致，我周末调试一下。

**Comment by tNobuta** [comment]
> 感谢，这几天我也发现了这个问题。在以前的Rust版本是没问题的，怀疑是Rust的Box < Callback > 被废弃导致，我周末调试一下。

是“dyn Callback”语法变更的兼容问题？

**Comment by tNobuta** [comment]
> > 感谢，这几天我也发现了这个问题。在以前的Rust版本是没问题的，怀疑是Rust的Box < Callback > 被废弃导致，我周末调试一下。
> 
> 也就是说trait object换成"dyn Callback" 应该就好了？我也去试试

好吧，还是需要把rsbind的针对callback的相关解析逻辑调整下才行

**Comment by sidneywang** [comment]
周末调查了一下，应该不是原先怀疑的问题。发现回调java的时候报错了。还需要进一步调查。

**Comment by tNobuta** [comment]
> 周末调查了一下，应该不是原先怀疑的问题。发现回调java的时候报错了。还需要进一步调查。

结案了。。。

因为Rsbind feature没有被认为是打开的，所以“JNI_OnLoad”方法没有参与编译，导致jvm对象是none

**Comment by sidneywang** [comment]
我的锅，之前重构引入了ndk-build, 导致features在编译时被去掉了。感谢感谢！

**Comment by sidneywang** [comment]
哥们想一起维护这个库吗，我有时候时间有点不够。

**Comment by sidneywang** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/6351028/153998606-408150a4-0a74-48e2-a22a-623b1761f228.png">
之前这里编译报错，觉得去掉应该没事，就去掉了。

**Comment by tNobuta** [comment]
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/6351028/153998606-408150a4-0a74-48e2-a22a-623b1761f228.png">
> 
> 之前这里编译报错，觉得去掉应该没事，就去掉了。

原来如此。。。
另外我看生成的rust wrapper代码里大量使用unwrap, 这里是否可以考虑用if let来取值呢，毕竟unwrap失败会抛panic,感觉有点风险 = =

**Comment by tNobuta** [comment]
另外有一个地方想请教下～ 目前这套rsbind工具无法针对“dyn Callback”这样的trait object语法进行有效解析，会得到void类型的参数类型，不知道这是syn库的问题，还是rsbind内部解析代码不兼容的问题

**Comment by sidneywang** [comment]
> 

可以啊，不过生成代码就比较复杂了，需要写更多的代码。未来可以优化。

**Comment by sidneywang** [comment]
> 另外有一个地方想请教下～ 目前这套rsbind工具无法针对“dyn Callback”这样的trait object语法进行有效解析，会得到void类型的参数类型，不知道这是syn库的问题，还是rsbind内部解析代码不兼容的问题

Rsbind的原理是先解析contract和imp目录下的rust语法树，然后根据语法树生成代码。需要针对dyn Callback这样的方式做特殊处理才行。现在只支持了Box<Callback>.

**Comment by tNobuta** [comment]
> > 另外有一个地方想请教下～ 目前这套rsbind工具无法针对“dyn Callback”这样的trait object语法进行有效解析，会得到void类型的参数类型，不知道这是syn库的问题，还是rsbind内部解析代码不兼容的问题
> 
> Rsbind的原理是先解析contract和imp目录下的rust语法树，然后根据语法树生成代码。需要针对dyn Callback这样的方式做特殊处理才行。现在只支持了Box.

嗯， 不过现在是针对box< dyn callback > 也无法正常解析出callback类型的方法入参

**Comment by sidneywang** [comment]
新代码已经提交，修复了该问题。
